package br.com.alelo.utils.setupTestes.query;

public class QueryPreparaBancoArv {
	
	public StringBuilder roternaUpdateDataDeProcessmentoAM() {
		StringBuilder sql = new StringBuilder(
				"update OWADQ.TCFG_PROCM set DT_PROCM = sysdate");
		System.out.println(sql);
		return sql;
	}
	
	public StringBuilder roternaUpdateDataDeProcessmentoPM() {
		StringBuilder sql = new StringBuilder(
				"update OWADQ.TCFG_PROCM set DT_PROCM = sysdate -1");
		return sql;
		
	}
	
	public StringBuilder roternaUpdateIdSolicitacao() {
		StringBuilder sql = new StringBuilder(
				"UPDATE owadq.tarv_rsumo_oper_dispn SET id_soltc = null WHERE id_pssoa_und =436623");
		return sql;
		
	}
	public StringBuilder roternaDeletePlanoRecorrente() {
		StringBuilder sql = new StringBuilder(
				"DELETE OWADQ.tsgm_contr where nu_cnpj = 54203102000133");
		return sql;
		
	}
	public StringBuilder roternaDeleteTaxas() {
		StringBuilder sql = new StringBuilder(
				"DELETE  OWADQ.TARV_CONFG_CANAL WHERE id_pssoa_und = 436623");
		return sql;
		
	}
	
	public StringBuilder roternaDeleteTransArv() {
		StringBuilder sql = new StringBuilder(
				"Delete OWADQ.TARV_RSUMO_OPER_DISPN WHERE id_pssoa_und = 436623");
		return sql;
		
	}
	public StringBuilder retornaInsertTransArv() {
					StringBuilder sql = new StringBuilder(" INSERT ALL ")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','682,44','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','225,6','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','752','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','2676,05','2,01',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','1504','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','198,34','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','8,46','0',sysdate,null)") 
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','77,08','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','682,44','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','225,6','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','752','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','2676,05','2,01',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','1504','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','198,34','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','8,46','0',sysdate,null)") 
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','77,08','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','682,44','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','225,6','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','752','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','2676,05','2,01',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','1504','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','198,34','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','8,46','0',sysdate,null)") 
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','77,08','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','682,44','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','225,6','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','752','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','2676,05','2,01',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','1504','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','198,34','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','8,46','0',sysdate,null)") 
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','77,08','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','682,44','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','225,6','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','752','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','2676,05','2,01',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','1504','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','198,34','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','8,46','0',sysdate,null)") 
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','77,08','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','682,44','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','225,6','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','752','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','2676,05','2,01',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200729', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','1504','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','198,34','0',sysdate,null)")
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','8,46','0',sysdate,null)") 
							.append(" into OWADQ.TARV_RSUMO_OPER_DISPN (ID_PSSOA_UND,NU_RSUMO_OPER_ORIGE,DT_VCTO_RSUMO_OPER,QT_DIA_CORRI,VR_ANTEC_DISP,VR_DESC,DT_PROCM,ID_SOLTC) values ('436623','5200730', TO_CHAR(sysdate+15,'DD/MM/YYYY'),'10','77,08','0',sysdate,null)")
							.append("  SELECT 1 FROM DUAL ");

					System.out.println(sql);
					return sql;
				}
	
	public StringBuilder retornaInsertTxsArv() {
		StringBuilder sql = new StringBuilder(" INSERT ALL ")
				.append(" into OWADQ.TARV_CONFG_CANAL (ID_PSSOA_UND,CD_CANAL,PC_TARIF,PC_TX_MES,PC_TX_PRORATA,PC_TX_PRORATA_PONDE,PC_PZ_PRORATA,DT_PROCM) values ('436623','1','0','11,55','3,85','103,03','26760,5',sysdate)")
				.append(" into OWADQ.TARV_CONFG_CANAL (ID_PSSOA_UND,CD_CANAL,PC_TARIF,PC_TX_MES,PC_TX_PRORATA,PC_TX_PRORATA_PONDE,PC_PZ_PRORATA,DT_PROCM) values ('436623','4','0','11,55','3,85','103,03','26760,5',sysdate)")
				.append(" into OWADQ.TARV_CONFG_CANAL (ID_PSSOA_UND,CD_CANAL,PC_TARIF,PC_TX_MES,PC_TX_PRORATA,PC_TX_PRORATA_PONDE,PC_PZ_PRORATA,DT_PROCM) values ('436623','2','0','11,55','3,85','103,03','26760,5',sysdate)")
				.append(" into OWADQ.TARV_CONFG_CANAL (ID_PSSOA_UND,CD_CANAL,PC_TARIF,PC_TX_MES,PC_TX_PRORATA,PC_TX_PRORATA_PONDE,PC_PZ_PRORATA,DT_PROCM) values ('436623','3','0','11,55','38500','103,03','26760,5',sysdate)")
				.append("  SELECT 1 FROM DUAL ");

		return sql;
	}
				
	

}
